### ISSUE TITLE
コンテンツの制御機能(通報機能)

### ISSUE THREAD

**Issue by sakiyamaK** [MiuraToya/LessonInfoApp#57]
SNS的な機能の場合必須
ユーザが望んでいない情報は非表示にできるようにしないといけない
これがないと審査に落ちる

フォロー、リフォロー、ブロック、ミュートなど

**Comment by MiuraToya** [comment]
> SNS的な機能の場合必須
> ユーザが望んでいない情報は非表示にできるようにしないといけない
> これがないと審査に落ちる
> 
> フォロー、リフォロー、ブロック、ミュートなど

こちらは、通報機能という形でコンテンツを制御することにしました。
